name: Build GameHub IPA
on: [push]

jobs:
  build:
    runs-on: macos-14
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Node 24 ব্যবহারের জন্য
    steps:
      - uses: actions/checkout@v4

      - name: Setup Folders and Tools
        run: |
          mkdir -p GameHub
          brew install xcodegen

      - name: Generate Entitlements (For JIT & Performance)
        run: |
          cat <<EOF > GameHub/GameHub.entitlements
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>dynamic-codesigning</key>
              <true/>
              <key>com.apple.developer.kernel.increased-memory-limit</key>
              <true/>
              <key>get-task-allow</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Fix Xcode Format and Generate
        run: xcodegen generate

      - name: Build Archive
        run: |
          xcodebuild archive -project GameHub.xcodeproj \
          -scheme GameHub -sdk iphoneos17.5 \
          -archivePath GameHub.xcarchive \
          CODE_SIGNING_ALLOWED=NO

      - name: Export IPA for Sideloading
        run: |
          mkdir -p Payload
          cp -r GameHub.xcarchive/Products/Applications/GameHub.app Payload/
          zip -r GameHub.ipa Payload
          
      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: Sifat-GameHub-Final
          path: GameHub.ipa
